[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'php82Extensions.mbstring', 'php82Extensions.openssl', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.bcmath', 'php82Packages.composer']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction'
]

[phases.build]
cmds = [
  'php artisan storage:link --force || true'
]

[start]
cmd = 'sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"'
